[package]
name = "dfutures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.4"
futures = { version = "0.3.28", features = ["thread-pool"] }
once_cell = "1.19.0"
tokio = { version = "1.32.0", features = ["full"] }
