[package]
name = "drayon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
pprof = { version = "0.13.0", features = ["flamegraph"] }
rayon = "1.7.0"
scoped-tls = "1.0.1"
