[package]
name = "mdp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
pulldown-cmark = "0.9.2"
wasmtime = "4.0.0"
anyhow = "1.0.68"