[package]
name = "embed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "4.0.0"
anyhow = "1.0.68"
wasmtime-wasi = "4.0.0"