###
GET http://127.0.0.1:8000/

###
GET http://127.0.0.1:8000/notfound

###
GET http://127.0.0.1:8000/json_api

###
POST http://127.0.0.1:8000/json_api
Content-Type: application/json

{
    "name": "Lily",
    "age":24
}

###
GET http://127.0.0.1:8000/test.html
